### ISSUE TITLE
rffmpeg fallback/localhost option

### ISSUE THREAD

**Issue by bubylou** [aleksasiriski/rffmpeg-go#13]
Wouldn't this break rffmpeg ability to use the fallback/localhost option of using ffmpeg in the same container since there is no real ffmpeg in the PATH anymore?  You could instead not symlink rffmpeg and instead change the jellyfin command line options to use rffmpeg. I'd be happy to open a PR for this if needed.

https://github.com/aleksasiriski/rffmpeg-go/blob/cc22d30b36f481415e4dacb5b772278c3335173f/apps/rffmpeg-go/Dockerfile#L6

**Comment by aleksasiriski** [comment]
No, it wouldn't.
Jellyfin by default (and rffmpeg-go) explicitly use `/usr/lib/jellyfin-ffmpeg/ffmpeg` as the real ffmpeg target.

You could look up commit history and see that, before I switched to onedr0p's image as the base, there was a command line option added to change the default ffmpeg to rffmpeg-go binary, but since onedr0p doesn't expose that you now have to manually change the line in Jellyfin's transcoding settings to `/usr/local/bin/ffmpeg`
